export default function() {
    return [
        {
            "slno": "120967734",
            "title": "डिनर के बाद इस मां ने बच्चों को सुलाया मौत की नींद, फिर किया सुसाइड",
            "filename": "gorakhpur-mother-kills-two-children-before-committing-suicide-5874941",
            "file_name": "gorakhpur-mother-kills-two-children-before-committing-suicide-5874941.html",
            "slug_intro": "सुबह स्कूल के लिए जगाने पहुंची दादी तो दिखा दहलाने वाला मंजर।",
            "channel_slno": "521",
            "cat_id": "5658",
            "priority_level_1": "12",
            "story_id": "121862017",
            "storyid": "121862017",
            "imageId": "121862017",
            "flag_v": "1",
            "video_flag": "1",
            "url": "https://m.bhaskar.com/news/gorakhpur-mother-kills-two-children-before-committing-suicide-5874941.html?ref=fpreco",
            "link": "https://m.bhaskar.com/news/gorakhpur-mother-kills-two-children-before-committing-suicide-5874941.html?ref=fpreco",
            "tpvs": "",
            "cat_type": "NEWS-FPRECO",
            "image": "https://i3.dainikbhaskar.com/thumbnails/351x303/web2images/www.bhaskar.com/2018/05/17/gorakhpur_1526554076.jpg",
            "image_attr": "width=\"196\" height=\"147\"",
            "targetblank": "",
            "image_count": "4",
            "traffic": "4857",
            "pubdate": "2018-05-17 18:20:00",
            "created_on": "2018-05-17 04:05:00",
            "pcat_id": "2052",
            "pcat_name": "Uttar Pradesh",
            "firstParagraph": "गोरखपुर.</b> यहां कैंट थाना क्षेत्र में गुरुवार सुबह एक महिला ने अपने दो बच्चों समेत सुसाइड कर लिया। परिजनों के मुताबिक मृतका दो साल से डिप्रेशन का शिकार थी। पुलिस ने शवों को कब्जे में लेकर पोस्टमॉर्टम के लिए भेज दिया है।</p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 4,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/05/17/gorakhpur_1526554076.jpg",
            "cat_url": "uttar-pradesh/gorakhpur/"
        },
        {
            "slno": "120967794",
            "title": "ग्वालियर में बहू ने लगाया रेप का आरोप, दुखी ससुर ने शर्मिंदगी में लगाई फांसी",
            "filename": "bahu-accused-of-rapd-in-gwalior-5875034",
            "file_name": "bahu-accused-of-rapd-in-gwalior-5875034.html",
            "slug_intro": "मृतक के बेटे का कहना है उसकी पत्नी ने उसके पिता के खिलाफ झूठा मामला दर्ज कराया है।",
            "channel_slno": "521",
            "cat_id": "6729",
            "priority_level_1": "12",
            "story_id": "121862128",
            "storyid": "121862128",
            "imageId": "121862128",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/bahu-accused-of-rapd-in-gwalior-5875034.html?ref=fpreco",
            "link": "https://m.bhaskar.com/news/bahu-accused-of-rapd-in-gwalior-5875034.html?ref=fpreco",
            "tpvs": "",
            "cat_type": "NEWS-FPRECO",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/05/17/untitled10_1526561143.jpg",
            "image_attr": "width=\"351\" height=\"273\"",
            "targetblank": "",
            "image_count": "2",
            "traffic": "3122",
            "pubdate": "2018-05-17 19:10:00",
            "created_on": "2018-05-17 06:05:00",
            "pcat_id": "1739",
            "pcat_name": "Madhya Pradesh",
            "firstParagraph": "ग्वालियर.</b>  शहर के थाटीपुर इलाके में बहू द्वारा रेप का मामला दर्ज कराने से दुखी ससुर ने शर्मिंदगी से बचने के लिए फांसी लगाकर खुदकुशी कर ली। थाटीपुर थाना पुलिस ने केस दर्ज कर जांच शुरू कर दी है। मृतक रमेशचंद्र रजक चतुर्थ श्रेणी कर्मचारी है। </p>\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/05/17/untitled10_1526561143.jpg",
            "cat_url": "mp/bhopal/"
        },
        {
            "slno": "120967527",
            "title": "शादीशुदा प्रेमिका से मिलने पहुंचा था प्रेमी, महिला के पति-ससुर ने करवा दी दूसरी शादी",
            "filename": "latest-gaya-LCL-girlfriend-to-meet-girlfriend-375-NOR",
            "file_name": "latest-gaya-LCL-girlfriend-to-meet-girlfriend-375-NOR.html",
            "slug_intro": "विवाहिता के चरित्र पर पति और ससुर ने उठाया सवाल, घर पर रखने से किया इनकार।",
            "channel_slno": "521",
            "cat_id": "7650",
            "priority_level_1": "12",
            "story_id": "121861638",
            "storyid": "121861638",
            "imageId": "121861638",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/latest-gaya-LCL-girlfriend-to-meet-girlfriend-375-NOR.html?ref=fpreco",
            "link": "https://m.bhaskar.com/news/latest-gaya-LCL-girlfriend-to-meet-girlfriend-375-NOR.html?ref=fpreco",
            "tpvs": "",
            "cat_type": "NEWS-FPRECO",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/05/17/fdfads_1526528073.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "1",
            "traffic": "6588",
            "pubdate": "2018-05-17 12:54:00",
            "created_on": "2018-05-17 08:05:00",
            "pcat_id": "3679",
            "pcat_name": "Bihar",
            "firstParagraph": "गया (बिहार)। </b>शादी के बाद प्रेमी से मिलना एक महिला को भारी पड़ गया। गया जिले के थाना क्षेत्र में बुधवार को एक विवाहिता की दूसरी शादी उसके प्रेमी पंकज के साथ खुद महिला के पति और ससुर ने करवा दी। जानकारी के अनुसार, 2017 में पप्पू और करिश्मा की शादी हुई थी। इस बीच लड़की का एक अन्य लड़के से अफेयर चल रहा था। इसका खुलासा मंगलवार की रात हुआ जब प्रेमी लड़की से मिलने उसके गांव पहुंचा । इस बात की भनक गांववालों को लगी। लोगों ने प्रेमी को पकड़कर, घटना की सूचना पुलिस और प्रेमी के भाई को दी।",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/05/17/fdfads_1526528073.jpg",
            "cat_url": "bihar/gaya/"
        },
        {
            "slno": "120967689",
            "title": "7 इंस्ट्रक्टर, 45 लोग लेकिन किसी ने नहीं देखा...और डूब गया 13 साल का हर्ष",
            "filename": "child-drowned-in-swimming-pool-no-body-helped-5874880",
            "file_name": "child-drowned-in-swimming-pool-no-body-helped-5874880.html",
            "slug_intro": "मामला सूरत के कापडिया हेल्थ क्लब का है। परिजनों ने संचालक के खिलाफ कार्रवाई की मांग की है।",
            "channel_slno": "521",
            "cat_id": "5858",
            "priority_level_1": "12",
            "story_id": "121861944",
            "storyid": "121861944",
            "imageId": "121861944",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/child-drowned-in-swimming-pool-no-body-helped-5874880.html?ref=fpreco",
            "link": "https://m.bhaskar.com/news/child-drowned-in-swimming-pool-no-body-helped-5874880.html?ref=fpreco",
            "tpvs": "",
            "cat_type": "NEWS-FPRECO",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/05/17/maa6_1526552331.jpg",
            "image_attr": "width=\"116\" height=\"87\"",
            "targetblank": "",
            "image_count": "3",
            "traffic": "9953",
            "pubdate": "2018-05-17 15:52:00",
            "created_on": "2018-05-17 03:05:00",
            "pcat_id": "2313",
            "pcat_name": "Gujarat",
            "firstParagraph": "सूरत (गुजरात). </b>शहर में बुधवार शाम तैराकी सीखने गए 13 साल के एक बच्चे की डूबने से मौत हो गई। लापरवाही का आलम ये रहा कि महज 15 दिन से तैराकी सीखने जा रहे इस बच्चे को बिना फ्लोटर के पूल में उतार दिया गया। घटना के वक्त 6 इंस्ट्रक्टर सहित 45 लोग मौके पर मौजूद थे। लेकिन किसी का ध्यान डूबते बच्चे की ओर नहीं गया। मामला कापडिया हेल्थ क्लब के स्विमिंग पूल का है। परिजनों ने क्लब संचालक के खिलाफ कार्रवाई की मांग की है। मां चीखती रही, मेरा बेटा डूब रहा है लेकिन...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/05/17/maa6_1526552331.jpg",
            "cat_url": "gujarat/surat/"
        },
        {
            "slno": "120305500",
            "title": "स्त्री हो या पुरुष बिना नहाए करें ये शुभ काम, चमक सकती है आपकी किस्मत",
            "filename": "JM-JYO-RAN-UTLT-old-tradition-about-sun-rise-time-dhan-prapti-ke-upay-jyotish-ke-upay-in-hindi-5796175-PHO",
            "file_name": "JM-JYO-RAN-UTLT-old-tradition-about-sun-rise-time-dhan-prapti-ke-upay-jyotish-ke-upay-in-hindi-5796175-PHO.html",
            "slug_intro": "ज्योतिष के उपाय लंबे समय तक करते रहने से किस्मत का साथ मिल सकता है।",
            "channel_slno": "3322",
            "cat_id": "9867",
            "priority_level_1": "12",
            "story_id": "121073526",
            "storyid": "121073526",
            "imageId": "121073526",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/JM-JYO-RAN-UTLT-old-tradition-about-sun-rise-time-dhan-prapti-ke-upay-jyotish-ke-upay-in-hindi-5796175-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/JM-JYO-RAN-UTLT-old-tradition-about-sun-rise-time-dhan-prapti-ke-upay-jyotish-ke-upay-in-hindi-5796175-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/religion.bhaskar.com/2018/01/21/wake_up_girl_2_1516519067.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "3",
            "traffic": "4534",
            "pubdate": "2018-01-21 17:00:00",
            "created_on": "2018-01-21 05:01:00",
            "pcat_id": "3362",
            "pcat_name": "Jyotish",
            "firstParagraph": "जिन लोगों की कुंडली में नौ ग्रहों से संबंधित कोई दोष होता है, उन्हें देवी-देवताओं की कृपा भी नहीं मिल पाता है। इसकी वजह से कार्यों में असफलता मिलती है, भाग्य साथ नहीं देता, घर-परिवार में अशांति रहती है। कुंडली के दोष और दुर्भाग्य को दूर करने के लिए ज्योतिष में कई उपाय बताए गए हैं। आमतौर पर अधिकतर उपाय या पूजा-पाठ नहाने के बाद ही करना चाहिए, लेकिन कुछ ऐसे शुभ काम भी हैं जो बिना नहाए किए जा सकते हैं। जानिए ऐसे ही कुछ खास शुभ काम...</p>\r\n\r\n </p>\r\n\r\nसुबह जागते ही करें इस मंत्र का जाप</b></p>\r\n\r\nस्त्री हो या पुरुष रोज सुबह जागते ही इस मंत्र का जाप अवश्य करें।</p>\r\n\r\nमंत्र-</p>\r\n\r\nब्रह्मा मुरारिस्त्रिपुरान्तकारी भानुः शशी भूमिसुतो बुधश्च।</b></p>\r\n\r\nगुरुश्च शुक्रः शनि राहुकेतवः कुर्वन्तु सर्वे ममसुप्रभातम्॥</b></p>\r\n\r\nइस मंत्र का जाप करने से सभी देवी-देवता और नौ ग्रहों की कृपा मिलती है। इस मंत्र का अर्थ यह है कि ब्रह्मा, विष्णु, शिव, सूर्य, चंद्र, मंगल, बुध, बृहस्पति, शुक्र, शनि, राहु और केतु ये सभी मेरे प्रातःकाल यानी सुबह को मंगलमय बनाएं।</p>\r\n\r\nये शुभ काम सुबह जागते ही करने से दुर्भाग्य से मुक्ति मिल सकती है।</p>\r\n\r\n </p>\r\n\r\nहथेलियां देखें</b></p>\r\n\r\nहमारे हाथों के अग्रभाग में देवी लक्ष्मी, मध्य में सरस्वती और हाथ के मूलभाग में भगवान विष्णु का वास है। इसलिए सुबह जागते ही अपनी दोनों हथेलियों को देखकर मंत्र का पाठ करना चाहिए-</p>\r\n\r\nकराग्रे वसते लक्ष्मीः करमध्ये सरस्वती।</b></p>\r\n\r\nकरमूले तू गोविंद: प्रभाते करदर्शनम्॥</b></p>\r\n\r\n </p>\r\n\r\nब्रह्म मुहूर्त में ही छोड़ देना चाहिए बिस्तर</b></p>\r\n\r\nशास्त्रों के अनुसार व्यक्ति को ब्रह्म मुहूर्त यानी सूर्य से पहले ही बिस्तर छोड़ देना चाहिए। जो व्यक्ति सुबह देर तक सोता है, उसकी बुद्धि कम होती है और दुर्भाग्य बढ़ता है।</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/religion.bhaskar.com/2018/01/21/wake_up_girl_2_1516519067.jpg",
            "cat_url": ""
        }
       /* {
            "slno": "120305684",
            "title": "इस लड़की के लिए IPS ने कैंसिल कराया था टिकट, यहां से शुरू हुई लव स्टोरी",
            "filename": "UP-LUCK-LCL-special-story-of-ips-marriage-life-in-lucknow-5796291-PHO",
            "file_name": "UP-LUCK-LCL-special-story-of-ips-marriage-life-in-lucknow-5796291-PHO.html",
            "slug_intro": "देश के 3 राज्यों में 27 नाटकों के 280 से भी ज्यादा शो कर चुकी सीमा मोदी।",
            "channel_slno": "521",
            "cat_id": "8172",
            "priority_level_1": "12",
            "story_id": "121073792",
            "storyid": "121073792",
            "imageId": "121073792",
            "flag_v": "1",
            "video_flag": "1",
            "url": "https://m.bhaskar.com/news/UP-LUCK-LCL-special-story-of-ips-marriage-life-in-lucknow-5796291-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/UP-LUCK-LCL-special-story-of-ips-marriage-life-in-lucknow-5796291-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/lku_1516534266.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "4",
            "traffic": "4416",
            "pubdate": "2018-01-26 11:12:00",
            "created_on": "2018-01-21 04:01:00",
            "pcat_id": "2052",
            "pcat_name": "Uttar Pradesh",
            "firstParagraph": "लखनऊ. </b>देश के 3 राज्यों में 27 नाटकों के 280 से भी ज्यादा शो कर चुकी सीमा मोदी को यूपी की बहू के रूप में पुकारा जाता है। इस वक्त वो अपना पूरा फोकस अपने थिएटर आर्ट पर रख रही हैं। सीमा ने DainikBhaskar.com से बातचीत में अपनी शादी की बात को साझा किया। उन्होंने बताया, ''ये अपने किसी रिलेटीव की शादी में आए थे और मुझसे मिलने के लिए अपनी ट्रेन की टिकट तक कैंसिल करा दी।''</p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/lku_1516534266.jpg",
            "cat_url": "uttar-pradesh/lucknow/"
        },
        {
            "slno": "120305704",
            "title": "59 की उम्र में भी इतनी फिट हैं रणबीर कपूर की मॉम, ये है फिटनेस सीक्रेट",
            "filename": "ENT-CBA-IFTM-neetu-singh-rishi-kapoor-38th-marriage-anniversary-5796325-PHO",
            "file_name": "ENT-CBA-IFTM-neetu-singh-rishi-kapoor-38th-marriage-anniversary-5796325-PHO.html",
            "slug_intro": "नीतू सिंह और ऋषि कपूर की शादी की आज 38वीं सालगिरह है। दोनों ने 22 जनवरी, 1980 को शादी की थी।",
            "channel_slno": "521",
            "cat_id": "10830",
            "priority_level_1": "12",
            "story_id": "121073830",
            "storyid": "121073830",
            "imageId": "121073830",
            "flag_v": "1",
            "video_flag": "1",
            "url": "https://m.bhaskar.com/news/ENT-CBA-IFTM-neetu-singh-rishi-kapoor-38th-marriage-anniversary-5796325-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/ENT-CBA-IFTM-neetu-singh-rishi-kapoor-38th-marriage-anniversary-5796325-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/neetu-singh_1516538347.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "5",
            "traffic": "7236",
            "pubdate": "2018-01-22 18:30:00",
            "created_on": "2018-01-22 12:01:00",
            "pcat_id": "3998",
            "pcat_name": "Entertainment",
            "firstParagraph": "नीतू सिंह और ऋषि कपूर की शादी की आज 38वीं सालगिरह है। दोनों ने 22 जनवरी, 1980 को शादी की थी। ऋषि कपूर जहां 65 साल के हैं, वहीं नीतू 59 साल की है। बता दें कि इतनी उम्र में भी नीतू खुद को फिट रखती हैं। उनका फिटनेस मंत्र है एक्टिव रहना और जिम के पीछे न भागना। बता दें कि नीतू ने 1966 में बॉलीवुड में बतौर चाइल्ड आर्टिस्ट डेब्यू किया था। कुछ फिल्मों में बाल कलाकार के तौर पर काम करने के बाद उन्होंने फिल्म 'रिक्शावाला' से बतौर लीड एक्ट्रेस डेब्यू किया था। उनका बेटा रणबीर कपूर फिल्मों में एक्टिव है और बेटी रिद्धिमा फैशन डिजाइनर हैं। रोज चलती हैं 10 हजार कदम...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/neetu-singh_1516538347.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305765",
            "title": "दीदी और दोस्तों को देख रो पड़ा स्टूडेंट, लेडी टीचर की हत्या का यहां बनाया प्लान",
            "filename": "HAR-AMB-OMC-LCL-court-reject-bail-petition-of-murderer-of-lady-teacher-5796444-PHO",
            "file_name": "HAR-AMB-OMC-LCL-court-reject-bail-petition-of-murderer-of-lady-teacher-5796444-PHO.html",
            "slug_intro": "कोर्ट में स्टूडेंट की दादी, रिश्तेदार और दोस्त भी पहुंचे थे, जिन्हें देख बाप-बेटे की आंखों में आंसू आ गए।",
            "channel_slno": "521",
            "cat_id": "1732",
            "priority_level_1": "12",
            "story_id": "121073963",
            "storyid": "121073963",
            "imageId": "121073963",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/HAR-AMB-OMC-LCL-court-reject-bail-petition-of-murderer-of-lady-teacher-5796444-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/HAR-AMB-OMC-LCL-court-reject-bail-petition-of-murderer-of-lady-teacher-5796444-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/22/fr_1516564314.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "8",
            "traffic": "4354",
            "pubdate": "2018-01-28 06:30:00",
            "created_on": "2018-01-22 12:01:00",
            "pcat_id": "1742",
            "pcat_name": "Haryana",
            "firstParagraph": "यमुनानगर.</b> स्वामी विवेकानंद पब्लिक स्कूल की प्रिंसिपल रीतू छाबड़ा का हत्यारोपी स्टूडेंट शिवांश गुंबर  और आर्म्स एक्ट में नामजद उसके पिता रणजीत को पुलिस ने दोपहर करीब एक बजे ड्यूटी मजिस्ट्रेट जेएमआईसी प्रतिभा मेहला की कोर्ट में पेश किया। कोर्ट में स्टूडेंट की दादी, रिश्तेदार और दोस्त भी पहुंचे थे, जिन्हें देख बाप-बेटे की आंखों में आंसू आ गए।</p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/22/fr_1516564314.jpg",
            "cat_url": "harayana/ambala/"
        },
        {
            "slno": "120305966",
            "title": "GFको जबरन भगा ले गया था प्रेमी, डेढ़ साल बाद कार समेत जमीन मेें दबे मिले दोनों",
            "filename": "HAR-AMB-OMC-LCL-couple-dead-body-found-in-car-after-one-and-half-year-during-road-excavation-5796490-PHO",
            "file_name": "HAR-AMB-OMC-LCL-couple-dead-body-found-in-car-after-one-and-half-year-during-road-excavation-5796490-PHO.html",
            "slug_intro": "पृथ्वी के माजरा के पास नेशनल हाईवे बनाने के लिए खुदाई करते समय दलदल से मिली कार मेंं कोतरखाना गांव के नरेश और अंजू के शव",
            "channel_slno": "521",
            "cat_id": "1732",
            "priority_level_1": "12",
            "story_id": "121074203",
            "storyid": "121074203",
            "imageId": "121074203",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/HAR-AMB-OMC-LCL-couple-dead-body-found-in-car-after-one-and-half-year-during-road-excavation-5796490-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/HAR-AMB-OMC-LCL-couple-dead-body-found-in-car-after-one-and-half-year-during-road-excavation-5796490-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/22/untitled-22_1516570449.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "9",
            "traffic": "3123",
            "pubdate": "2018-01-28 06:30:00",
            "created_on": "2018-01-22 02:01:00",
            "pcat_id": "1742",
            "pcat_name": "Haryana",
            "firstParagraph": "यमुनानगर.</b> पृथ्वी के माजरा के पास नेशनल हाईवे बनाने के लिए खुदाई करते समय दलदल से मिली कार मेंं कोतरखाना गांव के नरेश और अंजू के शव होने का अनुमान है। दोनों अलग-अलग शादीशुदा थे। 7 जुलाई 2016 को 46 साल नरेश जबरदस्ती 38 साल की अंजू को कार में बैठा ले गया था। उसी दिन से दोनों लापता थे। पहले तो फैमिलीवाले उन्हें ढूंढते रहे, पुलिस में एफआईआर भी कराई। बाद में यह सोचकर चुप बैठ गए कि दोनों ने कहीं घर बसा लिया होगा। अब दोनों परिवारों ने उनके वापस आने की उम्मीद भी छोड़ दी थी।</p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/22/untitled-22_1516570449.jpg",
            "cat_url": "harayana/ambala/"
        },
        {
            "slno": "120306547",
            "title": "अवॉर्ड्स नाइट में एक्ट्रेस की ड्रेस पर टिकी हर नजर, फोटो शेयर की तो हुआ ये",
            "filename": "ENT-BOL-IFTM-urvashi-rautela-got-trolled-for-her-filmfare-dress-5796796-PHO",
            "file_name": "ENT-BOL-IFTM-urvashi-rautela-got-trolled-for-her-filmfare-dress-5796796-PHO.html",
            "slug_intro": "उर्वशी रौतेला शनिवार को फिल्मफेयर अवॉर्ड्स के रेड कार्पेट पर नजर आईं।",
            "channel_slno": "521",
            "cat_id": "4182",
            "priority_level_1": "12",
            "story_id": "121075002",
            "storyid": "121075002",
            "imageId": "121075002",
            "flag_v": "1",
            "video_flag": "1",
            "url": "https://m.bhaskar.com/news/ENT-BOL-IFTM-urvashi-rautela-got-trolled-for-her-filmfare-dress-5796796-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/ENT-BOL-IFTM-urvashi-rautela-got-trolled-for-her-filmfare-dress-5796796-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/22/urvashi-rautela_151660591.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "4",
            "traffic": "3446",
            "pubdate": "2018-01-22 18:58:00",
            "created_on": "2018-01-22 12:01:00",
            "pcat_id": "3998",
            "pcat_name": "Entertainment",
            "firstParagraph": "मुंबई.</b> 'सिंह साहब दि ग्रेट' (2013), 'सनम रे'(2016) और 'ग्रेट ग्रैंड मस्ती' (2016) जैसी फिल्मों में काम कर चुकीं एक्ट्रेस उर्वशी रौतेला शनिवार को फिल्मफेयर अवॉर्ड्स के रेड कार्पेट पर नजर आईं। इस दौरान उनके द्वारा पहनी गई belluccio की ब्लैक ड्रेस ने लोगों का ध्यान खींचा। उर्वशी इस ड्रेस में बेहद ग्लैमरस लग रही थीं। सेरेमनी के बाद उर्वशी ने इसी ड्रेस में अपनी कुछ फोटोज इंस्टाग्राम पर शेयर की। हालांकि, ये ग्लैमरस फोटोज पोस्ट करना उर्वशी के लिए परेशानी का सबब बन गया। लोगों ने दी पोर्न इंडस्ट्री में चले जाने की सलाह...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/22/urvashi-rautela_151660591.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305737",
            "title": "सुबह के नाश्ते में भूलकर भी न खाएं ये 5 चीजें, इनसे होते हैं इतने नुकसान",
            "filename": "LIF-STY-UTLT-we-should-not-eat-these-5-foods-in-breakfast-5796366-PHO",
            "file_name": "LIF-STY-UTLT-we-should-not-eat-these-5-foods-in-breakfast-5796366-PHO.html",
            "slug_intro": "ब्रेकफास्ट के लिए हमें सही फूड को चुनना चाहिए। ऐसी 5 चीजों के बारे में बता रहे हैं जो ब्रेकफास्ट में नहीं खाना चाहिए।",
            "channel_slno": "521",
            "cat_id": "5027",
            "priority_level_1": "12",
            "story_id": "121073883",
            "storyid": "121073883",
            "imageId": "121073883",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/LIF-STY-UTLT-we-should-not-eat-these-5-foods-in-breakfast-5796366-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/LIF-STY-UTLT-we-should-not-eat-these-5-foods-in-breakfast-5796366-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/5-nuksaan-670_1516543988.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "5",
            "traffic": "8348",
            "pubdate": "2018-01-25 12:41:00",
            "created_on": "2018-01-22 12:01:00",
            "pcat_id": "1532",
            "pcat_name": "Lifestyle",
            "firstParagraph": "यूटिलिटी डेस्क। </b>ब्रेकफास्ट दिन का सबसे इंर्पोटेंट मील होता है। अगर हम अच्छा ब्रेकफास्ट करते हैं तो हमारा पूरा दिन अच्छा जाता है। इसलिए ब्रेकफास्ट के लिए हमें सही फूड को चुनना चाहिए। यहां आपको ऐसी 5 चीजों के बारे में बता रहे हैं जो ब्रेकफास्ट में नहीं खाना चाहिए। इनसे वजन बढ़ने के साथ ही कई सारी हेल्द प्रॉब्लम्स आती हैं। आइए जानते हैं इनके बारे में। हेल्थ एक्सपर्ट डॉक्टर लिसा डेविस इन फूड्स के बारे में बता रही हैं, जो आपको ब्रेकफास्ट में नहीं खाना चाहिए।  </p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/5-nuksaan-670_1516543988.jpg",
            "cat_url": ""
        },
        {
            "slno": "120306360",
            "title": "शख्स का दावा : सन् 6000 में जाकर लौटा हूं, बताई भविष्य की ये बातें",
            "filename": "KZHK-IFTM-man-claims-to-travel-in-year-6000-5796708-PHO",
            "file_name": "KZHK-IFTM-man-claims-to-travel-in-year-6000-5796708-PHO.html",
            "slug_intro": "इस शख्स ने ऐसी बातें बताई हैं जिनपर यकीन करना मुश्किल है।",
            "channel_slno": "521",
            "cat_id": "7627",
            "priority_level_1": "12",
            "story_id": "121074755",
            "storyid": "121074755",
            "imageId": "121074755",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/KZHK-IFTM-man-claims-to-travel-in-year-6000-5796708-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/KZHK-IFTM-man-claims-to-travel-in-year-6000-5796708-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/22/time-travell1_1516597996.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "4",
            "traffic": "4915",
            "pubdate": "2018-01-23 12:54:00",
            "created_on": "2018-01-22 10:01:00",
            "pcat_id": "4184",
            "pcat_name": "Khabre Zara Hat ke",
            "firstParagraph": "हाल ही में एक शख्स ने दावा किया है कि वह भविष्य में सन् 6000 में जा चुका है। सोशल मीडिया पर वायरल हुए वीडियो में के मुताबिक एक पत्रकार ने इस शख्स का इंटरव्यू किसी अनजानी जगह पर लिया है। जिसमें इस शख्स ने ऐसी बातें बताई हैं जिनपर यकीन करना मुश्किल है। खोले ये राज...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/22/time-travell1_1516597996.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305550",
            "title": "रात 12 बजे तक ऑफर: Samsung का 6GB रैम वाला फोन 1568 रु. में ऐसे खरीदें",
            "filename": "LIF-STY-UTLT-samsung-galaxy-a8-online-sale-start-5796187-PHO",
            "file_name": "LIF-STY-UTLT-samsung-galaxy-a8-online-sale-start-5796187-PHO.html",
            "slug_intro": "सैमसंग के नए मिड रेंज फ्लैगशिप मॉडल Galaxy A8+ की सेलिंग शुरू हो चुकी है। ये सेल आज रात 12 बजे तक चलेगी।",
            "channel_slno": "521",
            "cat_id": "5027",
            "priority_level_1": "12",
            "story_id": "121073579",
            "storyid": "121073579",
            "imageId": "121073579",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/LIF-STY-UTLT-samsung-galaxy-a8-online-sale-start-5796187-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/LIF-STY-UTLT-samsung-galaxy-a8-online-sale-start-5796187-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/samsung_galaxy_a8_1_15165.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "6",
            "traffic": "6496",
            "pubdate": "2018-01-21 13:09:00",
            "created_on": "2018-01-21 12:01:00",
            "pcat_id": "1532",
            "pcat_name": "Lifestyle",
            "firstParagraph": "यूटिलिटी डेस्क।  </b>सैमसंग के नए मिड रेंज फ्लैगशिप मॉडल Galaxy A8+ की सेलिंग शुरू हो चुकी है। ये सेल आज रात 12 बजे तक चलेगी। कंपनी इस स्मार्टफोन को ई-कॉमर्स वेबसाइट अमेजन पर एक्सक्लूसिव सेल कर रही है। सैमसंग के इस फोन में डुअल-फ्रंट कैमरा के साथ 6GB रैम दी है। ये बेजललेस मॉडल है। इस फोन में कई स्पेशल कैमरा फीचर्स दिए गए हैं। इससे प्रोफेशनल फोटोग्राफी की जा सकती है। फोन की की कीमत 32,990 रुपए है। इसे 1,568 रुपए की नो कोस्ट EMI पर भी खरीद सकते हैं।</p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/samsung_galaxy_a8_1_15165.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305669",
            "title": "आलिया ने किया इस शख्स को Kiss, घर के बाहर ऐसी हालत में दिखे 'सिंघम'",
            "filename": "ENT-BNE-IFTM-alia-bhatt-to-ajay-devgan-celebs-spotted-at-different-places-5796250-PHO",
            "file_name": "ENT-BNE-IFTM-alia-bhatt-to-ajay-devgan-celebs-spotted-at-different-places-5796250-PHO.html",
            "slug_intro": "बीते दिनों कई बॉलीवुड सेलेब्स एयरपोर्ट पर नजर आए। आलिया भट्ट एयरपोर्ट पर फोटोग्राफर डब्बू रतनानी को किस करतीं स्पॉट हुईं",
            "channel_slno": "521",
            "cat_id": "8095",
            "priority_level_1": "12",
            "story_id": "121073748",
            "storyid": "121073748",
            "imageId": "121073748",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/ENT-BNE-IFTM-alia-bhatt-to-ajay-devgan-celebs-spotted-at-different-places-5796250-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/ENT-BNE-IFTM-alia-bhatt-to-ajay-devgan-celebs-spotted-at-different-places-5796250-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/celebs-spotted_1516529061.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "12",
            "traffic": "8925",
            "pubdate": "2018-01-22 08:20:00",
            "created_on": "2018-01-21 03:01:00",
            "pcat_id": "3998",
            "pcat_name": "Entertainment",
            "firstParagraph": "बीते दिनों कई बॉलीवुड सेलेब्स एयरपोर्ट पर नजर आए। आलिया भट्ट एयरपोर्ट पर फोटोग्राफर डब्बू रतनानी को किस करतीं स्पॉट हुईं। डब्बू एयरपोर्ट पर अपनी फैमिली के साथ नजर आए। इनके अलावा एयरपोर्ट तापसी पन्नू, कृति सेनन, अदिति राव हैदरी, ऐश्वर्या राय बच्चन, दीपिका पादुकोण सहित अन्य सेलेब्स नजर आए। अजय देवगन घर के बाहर ऐसी हालत में दिखे...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/celebs-spotted_1516529061.jpg",
            "cat_url": ""
        },
        {
            "slno": "120304883",
            "title": "वसंत पंचमी: आज के सितारे इन 8 राशियों के लिए रहेंगे खास",
            "filename": "JM-JYO-RAS-UTLT-todays-rashifal-22-january-monday-2018-free-daily-horoscope-5795892-PHO",
            "file_name": "JM-JYO-RAS-UTLT-todays-rashifal-22-january-monday-2018-free-daily-horoscope-5795892-PHO.html",
            "slug_intro": "पंचमी तिथि और मीन राशि का चंद्रमा 8 राशियों के लिए शुभ रहेगा। मकर राशि का सूर्य और मीन राशि का चंद्रमा शिवा योग बना रहे",
            "channel_slno": "3322",
            "cat_id": "3415",
            "priority_level_1": "12",
            "story_id": "121072642",
            "storyid": "121072642",
            "imageId": "121072642",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/JM-JYO-RAS-UTLT-todays-rashifal-22-january-monday-2018-free-daily-horoscope-5795892-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/JM-JYO-RAS-UTLT-todays-rashifal-22-january-monday-2018-free-daily-horoscope-5795892-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/religion.bhaskar.com/2018/01/20/rashifal-22-january-2018_.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "12",
            "traffic": "3513",
            "pubdate": "2018-01-21 17:00:00",
            "created_on": "2018-01-21 05:01:00",
            "pcat_id": "3362",
            "pcat_name": "Jyotish",
            "firstParagraph": "पंचमी तिथि और मीन राशि का चंद्रमा 8 राशियों के लिए शुभ रहेगा। मकर राशि का सूर्य और मीन राशि का चंद्रमा शिवा योग बना रहे हैं। इसके अलावा अब चंद्रमा पर शनि की टेढ़ी नजर भी नहीं है। इस कारण वृष, मिथुन, कन्या, तुला, वृश्चिक, मकर, कुंभ और मीन राशि वालों के लिए दिन शुभ रहेगा। इनके अलावा मेष, कर्क, सिंह और धनु राशि वाले लोगों को दिनभर संभलकर रहना होगा।</p>\r\n\r\n",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/religion.bhaskar.com/2018/01/20/rashifal-22-january-2018_.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305741",
            "title": "LIVE मैच में इस पुलिसवाले ने किया कुछ ऐसा, बैट्समैन भी देखता रह गया",
            "filename": "SPO-CRI-CRO-IFTM-cop-gets-around-himself-after-surprise-catch-in-aus-vs-eng-match-5796370-PHO",
            "file_name": "SPO-CRI-CRO-IFTM-cop-gets-around-himself-after-surprise-catch-in-aus-vs-eng-match-5796370-PHO.html",
            "slug_intro": "सेन्चुरी बनाने वाले जोस बटलर 'मैन ऑफ द मैच' बने। इस जीत के साथ ही इंग्लैंड ने 5 मैचों की सीरीज में 3-0 की बढ़त बना ली।",
            "channel_slno": "521",
            "cat_id": "5891",
            "priority_level_1": "12",
            "story_id": "121073889",
            "storyid": "121073889",
            "imageId": "121073889",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/SPO-CRI-CRO-IFTM-cop-gets-around-himself-after-surprise-catch-in-aus-vs-eng-match-5796370-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/SPO-CRI-CRO-IFTM-cop-gets-around-himself-after-surprise-catch-in-aus-vs-eng-match-5796370-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/front-pic_jpg2_1516546671.jpg",
            "image_attr": "width=\"116\" height=\"64\"",
            "targetblank": "",
            "image_count": "10",
            "traffic": "8668",
            "pubdate": "2018-01-21 23:52:00",
            "created_on": "2018-01-21 08:01:00",
            "pcat_id": "1053",
            "pcat_name": "Sports",
            "firstParagraph": "स्पोर्ट्स डेस्क.</b> सिडनी में रविवार को ऑस्ट्रेलिया और इंग्लैंड के बीच वनडे सीरीज का तीसरा मैच खेला गया। जिसे मेहमान टीम ने 16 रन से जीत लिया। मैच में ऑस्ट्रेलिया को जीत के लिए 303 रन का टारगेट मिला था। जवाब में वो 286/6 रन ही बना सकी। मैच के दौरान एक पुलिसवाला कुछ देर के लिए स्टार बन गया। दरअसल बाउंड्री के बाहर खड़े होकर ड्यूटी कर रहे इस कॉप ने अपने पास आई बॉल को बड़े ही शानदार अंदाज में कैच कर लिया। देखता रह गया बैट्समैन भी...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/front-pic_jpg2_1516546671.jpg",
            "cat_url": ""
        },
        {
            "slno": "120303741",
            "title": "दिखने लगे बॉडी में ये 5 संकेत तो समझ जाएं आपका लिवर है खतरे में",
            "filename": "LIF-STY-UTLT-5-signs-for-your-liver-might-be-at-risk-5794909-PHO",
            "file_name": "LIF-STY-UTLT-5-signs-for-your-liver-might-be-at-risk-5794909-PHO.html",
            "slug_intro": "यहां हम आपको कुछ ऐसे कॉमन सिम्टम बता रहे हैं जो लिवर के खतरे में होने का संकेत होते हैं।",
            "channel_slno": "521",
            "cat_id": "5027",
            "priority_level_1": "12",
            "story_id": "121070729",
            "storyid": "121070729",
            "imageId": "121070729",
            "flag_v": "1",
            "video_flag": "1",
            "url": "https://m.bhaskar.com/news/LIF-STY-UTLT-5-signs-for-your-liver-might-be-at-risk-5794909-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/LIF-STY-UTLT-5-signs-for-your-liver-might-be-at-risk-5794909-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/19/5-signs-for-your-liv.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "5",
            "traffic": "7717",
            "pubdate": "2018-01-22 11:08:00",
            "created_on": "2018-01-19 01:01:00",
            "pcat_id": "1532",
            "pcat_name": "Lifestyle",
            "firstParagraph": "यूटिलिटी डेस्क। </b>लिवर सिर्फ खून को ही फिल्टर नहीं करता यह हार्मोन को प्रोड्यूस करने के साथ ही एनर्जी को स्टोर करने, फूड को डाइजेस्ट करने का भी काम करता है। लिवर के हेल्थ पर ही पूरी बॉडी की हेल्थ डिपेंड करती है। अगर लिवर हेल्दी नहीं है तो आप हेल्दी नहीं रह सकते। यहां हम आपको कुछ ऐसे कॉमन सिम्टम बता रहे हैं जो लिवर के खतरे में होने का संकेत होते हैं। अगर आपको ये संकेत बॉडी में दिखाई दे रहे हैं तो आपको डॉक्टर के पास जाना चाहिए। </p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/19/5-signs-for-your-liv.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305692",
            "title": "पोस्ट ऑफिस की इस स्कीम में लगाएं पैसा, बचत खाते से डबल मिलेगा रिटर्न",
            "filename": "MON-MARK-STMF-MRKT-infog-this-small-saving-scheme-of-post-office-may-better-for-you-5796305-PHO",
            "file_name": "MON-MARK-STMF-MRKT-infog-this-small-saving-scheme-of-post-office-may-better-for-you-5796305-PHO.html",
            "slug_intro": "पोस्ट ऑफिस की इस स्माल सेविंग स्कीम का चुनाव कर सकते हैं, जहां बचत के पैसे पर ज्यादा रिटर्न पा सकते हैं।",
            "channel_slno": "1463",
            "cat_id": "8327",
            "priority_level_1": "12",
            "story_id": "121073808",
            "storyid": "121073808",
            "imageId": "121073808",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.money.bhaskar.com/news/MON-MARK-STMF-MRKT-infog-this-small-saving-scheme-of-post-office-may-better-for-you-5796305-PHO.html?ref=rec",
            "link": "https://m.money.bhaskar.com/news/MON-MARK-STMF-MRKT-infog-this-small-saving-scheme-of-post-office-may-better-for-you-5796305-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/112x80/web2images/www.businessbhaskar.com/2018/01/21/income_1516535420.jpg",
            "image_attr": "width=\"116\" height=\"77\"",
            "targetblank": "_blank",
            "image_count": "5",
            "traffic": "3539",
            "pubdate": "2018-01-24 11:19:00",
            "created_on": "2018-01-21 05:01:00",
            "pcat_id": "8325",
            "pcat_name": "Market",
            "firstParagraph": "नई दिल्‍ली।</b> अगर आज के दौर में 50 हजार से 1 लाख रुपए मंथली सैलरी है तो बहुत ज्यादा बचत संभव नहीं हो पाती है। नौकरीपेशा वालों में बहुत से लोग ऐसे हैं, जिनकी मंथली बचत 2, 3 या 5 हजार रुपए तक ही हो पाती है। ऐसे में बहुत से लोग इस बचत को बैंक की सेविंग अकाउंट में रखते हैं या इस तरह की किसी और स्कीम का विकल्प चुनते हैं। लेकिन हम आपको बता दें कि कुछ ऐसी स्कीम है, जिसके जरिए आप अपने बचत के पैसों पर ज्यादा फायदा पा सकते हैं, वह भी बेहद की सुरक्षित तरीके से। </p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 5,
            "infog": 1,
            "images": [
                "https://i3.dainikbhaskar.com/thumbnails/112x80/web2images/www.businessbhaskar.com/2018/01/21/income_1516535420.jpg",
                "https://i3.dainikbhaskar.com/thumbnails/112x80/web2images/www.businessbhaskar.com/2018/01/21/postoffice_1516535427.jpg",
                "https://i3.dainikbhaskar.com/thumbnails/112x80/web2images/www.businessbhaskar.com/2018/01/21/invest1_1516535445.jpg"
            ],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.businessbhaskar.com/2018/01/21/income_1516535420.jpg",
            "cat_url": ""
        },
        {
            "slno": "120303866",
            "title": "अगर आप भूतों पर विश्वास करते हैं, तो इन फोटोज को न देखें",
            "filename": "KZHK-IFTM-ghostly-pictures-can-you-believe-them-5795132-PHO",
            "file_name": "KZHK-IFTM-ghostly-pictures-can-you-believe-them-5795132-PHO.html",
            "slug_intro": "इन फोटोज को देखकर क्या आप बता सकते हैं कि इनमें आखिर ऐसा क्या हुआ होगा जिसके पीछे की गुत्थी आज तक कोई नहीं सुलझा पाया।",
            "channel_slno": "521",
            "cat_id": "7627",
            "priority_level_1": "12",
            "story_id": "121070999",
            "storyid": "121070999",
            "imageId": "121070999",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/KZHK-IFTM-ghostly-pictures-can-you-believe-them-5795132-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/KZHK-IFTM-ghostly-pictures-can-you-believe-them-5795132-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/19/ghostly-pictures8_1516365.jpg",
            "image_attr": "width=\"103\" height=\"80\"",
            "targetblank": "",
            "image_count": "9",
            "traffic": "8771",
            "pubdate": "2018-01-22 11:10:00",
            "created_on": "2018-01-19 06:01:00",
            "pcat_id": "4184",
            "pcat_name": "Khabre Zara Hat ke",
            "firstParagraph": "क्या आप भूतों पर भरोसा करते हैं? क्या इन फोटोज को देखकर क्या आप बता सकते हैं कि इनमें आखिर ऐसा क्या हुआ होगा जिसके पीछे की गुत्थी आज तक कोई नहीं सुलझा पाया। जी हां, आज हम आपको दिखा रहे हैं दुनियाभर की कुछ ऐसी फोटोज और उनसे जुड़े खौफनाक सच जो बेहद चौंकाने वाले हैं। इन फोटोज में कुछ ऐसी चीजें लोगों को नजर आईं जिसके पीछेे की वजह बताना बेहद मुश्किल है। या यूं कहें कि इन फोटोज में पैरानॉर्मल एक्टिविटी के होने से इंकार नहीं किया जा सकता। बच्चे के साथ भटकती मां की आत्मा...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/19/ghostly-pictures8_1516365.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305658",
            "title": "अब jio ने लॉन्च की 1 साल के लिए ये फ्री सर्विस, ऐसे करें इसका Use",
            "filename": "LIF-STY-UTLT-reliance-jio-users-to-get-eros-content-on-phones-now-5796219-PHO",
            "file_name": "LIF-STY-UTLT-reliance-jio-users-to-get-eros-content-on-phones-now-5796219-PHO.html",
            "slug_intro": "जियो शुरू से ही अपने यूसर्ज को ढ़ेरों फायदे दे रही है। अब कंपनी अपने यूजर्स के लिए एक और सरप्राइज लेकर आ गई है।",
            "channel_slno": "521",
            "cat_id": "5027",
            "priority_level_1": "12",
            "story_id": "121073714",
            "storyid": "121073714",
            "imageId": "121073714",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/LIF-STY-UTLT-reliance-jio-users-to-get-eros-content-on-phones-now-5796219-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/LIF-STY-UTLT-reliance-jio-users-to-get-eros-content-on-phones-now-5796219-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/jio_1516525804.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "2",
            "traffic": "8862",
            "pubdate": "2018-01-23 12:37:00",
            "created_on": "2018-01-21 02:01:00",
            "pcat_id": "1532",
            "pcat_name": "Lifestyle",
            "firstParagraph": "यूटिलिटी डेस्क।</b>  जियो शुरू से ही अपने यूसर्ज को ढ़ेरों फायदे दे रही है। कंपनी ने अब तक अपने यूजर्स के लिए कई ऑफर पेश किए हैं और अब कंपनी अपने यूजर्स के लिए एक और सरप्राइज लेकर आ गई है। जियो ने हाल ही में फिल्म निर्माता कंपनी इरोज इंटरनेशनल के साथ अपने करार को रिन्यू कर दिया है। जियो और इरोज इंटरनेशनल के इस कॉन्ट्रेक्ट के बाद यूजर्स फ्री में बॉलीवुड फिल्मों के साथ ही कई विदेशी फिल्में, जिनकी कई भाषाओं में सबटाइटल होंगे का मजा ले सकेंगे। </p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/jio_1516525804.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305670",
            "title": "मां के रूम से अचानक आने लगी चीखें, सीक्रेट कैमरे में कैद हुआ ऐसा मंजर",
            "filename": "UP-LUCK-LCL-woman-died-due-to-burn-captured-in-cctv-5796260-PHO",
            "file_name": "UP-LUCK-LCL-woman-died-due-to-burn-captured-in-cctv-5796260-PHO.html",
            "slug_intro": "बरेली में 50 साल की महिला ने 17 जनवरी को डिप्रेशन में आकर खुद को आग लगा ली। पूरी घटना रूम में लगे CCTV में कैद हो गई।",
            "channel_slno": "521",
            "cat_id": "8172",
            "priority_level_1": "12",
            "story_id": "121073758",
            "storyid": "121073758",
            "imageId": "121073758",
            "flag_v": "1",
            "video_flag": "1",
            "url": "https://m.bhaskar.com/news/UP-LUCK-LCL-woman-died-due-to-burn-captured-in-cctv-5796260-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/UP-LUCK-LCL-woman-died-due-to-burn-captured-in-cctv-5796260-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/op123_1516536663.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "3",
            "traffic": "4581",
            "pubdate": "2018-01-21 22:45:00",
            "created_on": "2018-01-21 02:01:00",
            "pcat_id": "2052",
            "pcat_name": "Uttar Pradesh",
            "firstParagraph": "बरेली(यूपी).  </b>यहां 50 साल की महिला ने 17 जनवरी को डिप्रेशन में आकर खुद को आग लगा ली। पहले महिला ने इधर-उधर से कपड़े इकठ्ठा किए। फिर फर्श पर रखकर मिट्टी का तेल छिड़क दिया। इसके बाद आग लगा दी। इधर-उधर से कपड़े इकठ्ठा करके मिट्टी का तेल छिड़क दिया। इसके बाद उसमें आग लगा दी। फिर उठती लपटें के बीच जाकर खड़ी हो गईं। चीखें सुनकर पहुंचे लोग...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/op123_1516536663.jpg",
            "cat_url": "uttar-pradesh/lucknow/"
        },
        {
            "slno": "120304668",
            "title": "विदेशी कुत्ता समझ घर ले आए इसे, ये निकला खतरनाक जानवर का बच्चा",
            "filename": "c-16-LCL-baby-bear-caught-in-a-village-chhattisgarh-ra0392-NOR",
            "file_name": "c-16-LCL-baby-bear-caught-in-a-village-chhattisgarh-ra0392-NOR.html",
            "slug_intro": "गांव में गन्ने के खेत में बच्चों को भालू का नवजात मिला जिसे बच्चे विदेशी नस्ल के डॉग का बच्चा समझ बैठे।",
            "channel_slno": "521",
            "cat_id": "6800",
            "priority_level_1": "12",
            "story_id": "121072131",
            "storyid": "121072131",
            "imageId": "121072131",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/c-16-LCL-baby-bear-caught-in-a-village-chhattisgarh-ra0392-NOR.html?ref=rec",
            "link": "https://m.bhaskar.com/news/c-16-LCL-baby-bear-caught-in-a-village-chhattisgarh-ra0392-NOR.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/20/bear-8_1516444085.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "7",
            "traffic": "6155",
            "pubdate": "2018-01-21 08:27:00",
            "created_on": "2018-01-20 12:01:00",
            "pcat_id": "1741",
            "pcat_name": "Chhatisgarh",
            "firstParagraph": "\r\nबलरामपुर।</b> वन परिक्षेत्र के पास स्थित गांव में गन्ने के खेत में बच्चों को भालू का नवजात मिला जिसे बच्चे विदेशी नस्ल के डॉग का बच्चा समझ बैठे। वे इसे घर लेकर आए। इधर इस बच्चे को देखने के लिए स्थानीय लोगों की भीड़ उमड़ पड़ी। इसी बीच वन विभाग को भी इसकी खबर लग गई और वे बच्चे को वन परिक्षेत्र कार्यालय ले आए। शुक्रवार को भालू के बच्चे को पशु चिकित्सालय लाया गया जहां उसका स्वास्थ्य परीक्षण किया गया। फिलहाल ये यहीं है और इसे देखने के लिए लोगों की भीड़ उमड़ रही है। जानिए पूरी घटना...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/20/bear-8_1516444085.jpg",
            "cat_url": "chhatisgarh/raipur/"
        },
        {
            "slno": "120305700",
            "title": "BMW से Audi तक, 'बालिका वधु' की एक्ट्रेस को सास ने गिफ्ट कीं इतनी महंगी कारें",
            "filename": "ENT-TV-IFTM-neha-marda-mother-in-law-gifted-luxury-cars-5796316-PHO",
            "file_name": "ENT-TV-IFTM-neha-marda-mother-in-law-gifted-luxury-cars-5796316-PHO.html",
            "slug_intro": "टीवी शो 'बालिका वधू' फेम नेहा मर्दा इन दिनों एक्टिंग वर्ल्ड से दूर हैं।",
            "channel_slno": "521",
            "cat_id": "4032",
            "priority_level_1": "12",
            "story_id": "121073821",
            "storyid": "121073821",
            "imageId": "121073821",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/ENT-TV-IFTM-neha-marda-mother-in-law-gifted-luxury-cars-5796316-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/ENT-TV-IFTM-neha-marda-mother-in-law-gifted-luxury-cars-5796316-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/neha-saas7_1516537329.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "10",
            "traffic": "6573",
            "pubdate": "2018-01-21 18:53:00",
            "created_on": "2018-01-22 12:01:00",
            "pcat_id": "3998",
            "pcat_name": "Entertainment",
            "firstParagraph": "मुंबई.</b> टीवी शो 'बालिका वधू' फेम नेहा मर्दा इन दिनों एक्टिंग वर्ल्ड से दूर हैं। फिलहाल वे सिर्फ अपनी मैरिड लाइफ पर ध्यान दे रही हैं। उन्होंने 2012 में पटना के बिजनेसमैन आयुष्मान अग्रवाल से शादी की थी। आपको जानकर हैरानी होगी की नेहा के ससुराल में उनके पति से ज्यादा उनकी सासु मां उन्हें प्यार कर करती हैं और अक्सर महंगे-महंगे तोहफे देती हैं। पहली एनिवर्सरी पर गिफ्ट में मिली थी BMW...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/neha-saas7_1516537329.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305702",
            "title": "AUS-ENG मैच में एक ही साइड में पहुंच गए दोनों बैट्समैन, फिर हुआ कुछ यूं",
            "filename": "SPO-CRI-IFTM-tim-paine-throw-hitting-jos-buttler-and-falling-him-safe-in-aus-vs-eng-odi-5796323-PHO",
            "file_name": "SPO-CRI-IFTM-tim-paine-throw-hitting-jos-buttler-and-falling-him-safe-in-aus-vs-eng-odi-5796323-PHO.html",
            "slug_intro": "इस मैच को जीतने के साथ ही इंग्लैंड ने पांच मैचों की सीरीज में 3-0 की बढ़त लेते हुए सीरीज को भी जीत लिया।",
            "channel_slno": "521",
            "cat_id": "5181",
            "priority_level_1": "12",
            "story_id": "121073828",
            "storyid": "121073828",
            "imageId": "121073828",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/SPO-CRI-IFTM-tim-paine-throw-hitting-jos-buttler-and-falling-him-safe-in-aus-vs-eng-odi-5796323-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/SPO-CRI-IFTM-tim-paine-throw-hitting-jos-buttler-and-falling-him-safe-in-aus-vs-eng-odi-5796323-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/8_1516537652.jpg",
            "image_attr": "width=\"116\" height=\"64\"",
            "targetblank": "",
            "image_count": "13",
            "traffic": "3417",
            "pubdate": "2018-01-22 09:33:00",
            "created_on": "2018-01-21 05:01:00",
            "pcat_id": "1053",
            "pcat_name": "Sports",
            "firstParagraph": "स्पोर्ट्स डेस्क.</b> इंग्लैंड ने ऑस्ट्रेलिया के खिलाफ रविवार को हुआ वनडे सीरीज का तीसरा मैच 16 रन से जीत लिया। इसके साथ ही उसने पांच मैचों की इस सीरीज में 3-0 की अजेय बढ़त भी बना ली। मैच में उस वक्त बेहद अजीबोगरीब स्थिति बन गई, जब इंग्लैंड की इनिंग के दौरान दोनों बैट्समैन क्रीज के एक ही तरफ पहुंच गए। ऐसे हुआ पूरा इंसीडेंट...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/8_1516537652.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305640",
            "title": "भूलकर भी न छूएं इन 6 में से कोई 1 चीज, वरना पीछे पड़ सकती है दरिद्रता",
            "filename": "JM-JKR-DHAJ-UTLT-vishnu-puran-and-its-tips-in-hindi-how-to-get-success-in-life-vishnu-puran-and-l-5796202-PHO",
            "file_name": "JM-JKR-DHAJ-UTLT-vishnu-puran-and-its-tips-in-hindi-how-to-get-success-in-life-vishnu-puran-and-l-5796202-PHO.html",
            "slug_intro": "पुराणों में बताई गई बातों का पालन करने पर बुरे समय से छुटकारा मिल सकता है।",
            "channel_slno": "3322",
            "cat_id": "9869",
            "priority_level_1": "12",
            "story_id": "121073687",
            "storyid": "121073687",
            "imageId": "121073687",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/JM-JKR-DHAJ-UTLT-vishnu-puran-and-its-tips-in-hindi-how-to-get-success-in-life-vishnu-puran-and-l-5796202-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/JM-JKR-DHAJ-UTLT-vishnu-puran-and-its-tips-in-hindi-how-to-get-success-in-life-vishnu-puran-and-l-5796202-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/religion.bhaskar.com/2018/01/21/vishnu_puran_1516522764.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "3",
            "traffic": "4243",
            "pubdate": "2018-01-21 13:50:00",
            "created_on": "2018-01-21 01:01:00",
            "pcat_id": "5228",
            "pcat_name": "Jeene Ki Rah",
            "firstParagraph": "रोड पर चलते समय कई प्रकार की चीजें दिखाई देती हैं। इन चीजों में कुछ अशुभ और नुकसानदायक भी होती हैं। यहां 6 ऐसी चीजें बताई जा रही हैं जो अशुभ हैं और अगर सड़क पर ये दिखाई दें तो इन्हें छूने से बचना चाहिए। इनसे दूर रहना चाहिए। इन्हें छूने से दुर्भाग्य का सामना करना पड़ सकता है।</p>\r\n\r\nविष्णु पुराण में लिखा है इन 6 अशुभ चीजों के बारे में</b></p>\r\n\r\nविष्णु पुराण में सुख-समृद्धि और पवित्रता बनाए रखने के लिए कई प्रकार के नियम बताए गए हैं। इन नियमों का पालन करने पर भगवान विष्णु और महालक्ष्मी के साथ ही सभी देवी-देवताओं की कृपा प्राप्त की जा सकती है। विष्णु पुराण में बताया गया है कि रास्ते में चलते समय किन वस्तुओं से दूर रहना चाहिए, अन्यथा परेशानियों और दुखों का सामना करना पड़ सकता है, इन चीजों से हमारी पवित्रता भी नष्ट हो जाती है। इसीलिए यहां बताई जा रही 6 चीजों से दूर रहना चाहिए।</p>\r\n\r\n1. बाल</b></p>\r\n\r\nकई बार ऐसा होता है कि किसी व्यक्ति के टूटे हुए केश यानी बाल रास्ते में दिखाई देते हैं। बालों को भी अपवित्र माना गया है। रास्ते में दिखाई देने वाले बालों से भी दूर होकर ही निकलना चाहिए। इन्हें लांघना भी नहीं चाहिए। यदि खाने में बाल गिर जाए तो पूरा खाना भी अपवित्र हो जाता है।</p>\r\n\r\n2. हड्डी</b></p>\r\n\r\nरोड पर दुर्घटनाएं होती रहती हैं और इन दुर्घटनाओं में कई बार जानवरों (जैसे कुत्ते, सांप आदि) की मौत हो जाती है। ऐसे में मरे हुए जीव की अस्थियां रोड पर बिखरी दिखाई देती हैं तो उनसे दूर होकर रास्ता पार करना चाहिए। अस्थियों के संपर्क में आने के बाद स्नान करना बहुत आवश्यक हो जाता है। शास्त्रों के अनुसार मृत जीव के संपर्क में आने के बाद हम अपवित्र हो जाते हैं, इसी वजह से किसी शव यात्रा में शामिल होने के तुरंत बाद स्नान करना आवश्यक बताया गया है।</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/religion.bhaskar.com/2018/01/21/vishnu_puran_1516522764.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305455",
            "title": "सूर्यास्त से पहले कर लें ये काम, दिमाग चलेगा तेज और मिलेगा धन लाभ",
            "filename": "JM-JYO-RAN-UTLT-basant-panchami-2018-basant-panchami-ke-upay-saraswati-mata-ke-upay-5796152-PHO",
            "file_name": "JM-JYO-RAN-UTLT-basant-panchami-2018-basant-panchami-ke-upay-saraswati-mata-ke-upay-5796152-PHO.html",
            "slug_intro": "बुद्धि तेज हो तो धन संबंधी कामों में सही समय पर सही निर्णय ले सकते हैं, जिससे धन लाभ मिलने के योग बन सकते हैं।",
            "channel_slno": "3322",
            "cat_id": "9867",
            "priority_level_1": "12",
            "story_id": "121073470",
            "storyid": "121073470",
            "imageId": "121073470",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/JM-JYO-RAN-UTLT-basant-panchami-2018-basant-panchami-ke-upay-saraswati-mata-ke-upay-5796152-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/JM-JYO-RAN-UTLT-basant-panchami-2018-basant-panchami-ke-upay-saraswati-mata-ke-upay-5796152-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/religion.bhaskar.com/2018/01/21/saraswati_devi_1_15165162.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "1",
            "traffic": "7725",
            "pubdate": "2018-01-21 17:00:00",
            "created_on": "2018-01-21 05:01:00",
            "pcat_id": "3362",
            "pcat_name": "Jyotish",
            "firstParagraph": "सोमवार, 22 जनवरी को बसंत पंचमी है। ये पर्व देवी सरस्वती को समर्पित है। इस दिन सरस्वतीजी की पूजा करने से देवी प्रसन्न होती है और उनकी कृपा से बुद्धि का विकास होता है। मां सरस्वती ज्ञान-विज्ञान, कला, संगीत की देवी हैं। बसंत पंचमी पर अज्ञानता को दूर करने और जीवन में नया उत्साह प्राप्त करने के लिए देवी सरस्वती को पूजा जाता है। देवी कृपा से दिमाग तेज चलता है और धन संबंधी कामों में सही निर्णय ले पाते हैं। जिससे लाभ के अवसर मिलते हैं। यहां जानिए बसंत पंचमी पर कौन-कौन से काम किए जा सकते हैं...</p>\r\n\r\nऐसे करें मां सरस्वती की पूजा</b></p>\r\n\r\nस्नान करने के बाद पीले या सफेद कपड़े पहनें। मां सरस्वती की मूर्ति या फोटो उत्तर-पूर्व दिशा में स्थापित करें। मां को सफेद चंदन, पीले और सफेद फूल चढ़ाएं। पूजा में सरस्वती मंत्र ऊँ ऐं सरस्वत्यै नम: का 108 बार जाप करें। मां सरस्वती की आरती करें। दूध, दही, तुलसी, शहद मिलाकर पंचामृत का प्रसाद बनाएं और भोग लगाएं।</p>\r\n\r\nबसंत पंचमी पर जरूर करें ये काम</b></p>\r\n\r\n1.</b> जिन लोगों की कुंडली में बुध ग्रह कमजोर है और पढ़ाई में मन नहीं लगता है तो बसंत पंचमी पर मां सरस्वती को फल चढ़ाएं। 11 गरीब बच्चों को फल बांटें।</p>\r\n\r\n2.</b> पढ़ाई करने वाले बच्चों को माता सरस्वती की तस्वीर अपने अध्ययन कक्ष में या टेबल पर रखना चाहिए। रोज देवी के दर्शन करें।</p>\r\n\r\n3.</b> अपनी पढ़ाई की टेबल पर क्रिस्टल या स्फटिक का ग्लोब रखें और उसे दिन में कम से कम तीन बार अवश्य घुमाएं।</p>\r\n\r\n4. </b>तुलसी के 11 पत्ते मिश्री के साथ निगल लें। ध्यान रखें तुलसी के पत्ते चबाना नहीं है।</p>\r\n\r\nये सभी उपाय करने से देवी सरस्वती की कृपा मिलती है और बुद्धि के साथ ही सुख-समृद्धि भी प्राप्त होती है।</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/religion.bhaskar.com/2018/01/21/saraswati_devi_1_15165162.jpg",
            "cat_url": ""
        },
        {
            "slno": "120304704",
            "title": "पति की मौत के बाद भी प्रेग्नेंट पत्नी ने नहीं मिटाया मांग का सिंदूर, चीखती रही",
            "filename": "MH-PUN-HMU-LCL-air-force-officer-martyr-mayur-patil-funeral-in-nandurbar-5795573-PHO",
            "file_name": "MH-PUN-HMU-LCL-air-force-officer-martyr-mayur-patil-funeral-in-nandurbar-5795573-PHO.html",
            "slug_intro": "गुजरात के बड़ौदा में एयरफोर्स के जवान मयूर पाटिल की परेड करते समय बेहोश होने के बाद मौत हुई।",
            "channel_slno": "521",
            "cat_id": "7188",
            "priority_level_1": "12",
            "story_id": "121072234",
            "storyid": "121072234",
            "imageId": "121072234",
            "flag_v": "1",
            "video_flag": "1",
            "url": "https://m.bhaskar.com/news/MH-PUN-HMU-LCL-air-force-officer-martyr-mayur-patil-funeral-in-nandurbar-5795573-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/MH-PUN-HMU-LCL-air-force-officer-martyr-mayur-patil-funeral-in-nandurbar-5795573-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/20/m-1_1516433197.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "7",
            "traffic": "6962",
            "pubdate": "2018-01-28 18:08:00",
            "created_on": "2018-01-20 12:01:00",
            "pcat_id": "2318",
            "pcat_name": "Maharashtra",
            "firstParagraph": "नंदूरबार.   </b> गुजरात के बड़ौदा में एयरफोर्स के जवान मयूर पाटिल की परेड करते समय बेहोश होने के बाद मौत हुई। मयूर पाटिल का अंतिम संस्कार शुक्रवार शाम सरकारी सम्मान के साथ किया गया। मयूर की पत्नी सात माह की प्रेग्नेंट है। वह अपने पति की बाॅडी के पास बैठकर उसे जगाने की कोशिश करती रही। वह बार-बार कह रह थी कि आप हमारा बच्चा देखे बिना ही हमसे दूर कैसे चले गए।  13 साल पहले ज्वाइन की थी एयरफोर्स...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/20/m-1_1516433197.jpg",
            "cat_url": "maharashtra/pune/"
        },
        {
            "slno": "120305447",
            "title": "टेस्ट सीरीज में मिली हार को भूल, साउथ अफ्रीका में यूं एन्जॉय कर रहे क्रिकेटर्स",
            "filename": "SPO-CRI-IFTM-indian-cricketers-enjoying-in-mziki-safari-in-south-africa-5796139-PHO",
            "file_name": "SPO-CRI-IFTM-indian-cricketers-enjoying-in-mziki-safari-in-south-africa-5796139-PHO.html",
            "slug_intro": "टीम के ज्यादातर मेंबर्स मजिकी सफारी पहुंचे, जो कि जोहानिसबर्ग से करीब 90 किलोमीटर दूर है।",
            "channel_slno": "521",
            "cat_id": "5723",
            "priority_level_1": "12",
            "story_id": "121073456",
            "storyid": "121073456",
            "imageId": "121073456",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/SPO-CRI-IFTM-indian-cricketers-enjoying-in-mziki-safari-in-south-africa-5796139-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/SPO-CRI-IFTM-indian-cricketers-enjoying-in-mziki-safari-in-south-africa-5796139-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/front-pic_1516512483.jpg",
            "image_attr": "width=\"116\" height=\"64\"",
            "targetblank": "",
            "image_count": "12",
            "traffic": "7249",
            "pubdate": "2018-01-21 23:17:00",
            "created_on": "2018-01-21 10:01:00",
            "pcat_id": "1053",
            "pcat_name": "Sports",
            "firstParagraph": "स्पोर्ट्स डेस्क. </b>साउथ अफ्रीका के हाथों टेस्ट सीरीज गंवाने के बाद इंडियन क्रिकेटर्स इन दिनों मौज-मस्ती के मूड में हैं। टीम इंडिया 3 मैचों की टेस्ट सीरीज के शुरुआती दोनों मैच हार चुकी है और तीसरा मैच 24 जनवरी से जोहानिसबर्ग में खेला जाएगा। आखिरी मैच शुरू होने से पहले इंडियन प्लेयर्स ने फैमिली के साथ एन्जॉय करते दिखे। टीम के ज्यादातर मेंबर्स मजिकी सफारी पहुंचे, जो कि जोहानिसबर्ग से करीब 90 किलोमीटर दूर है। इस दौरान प्लेयर्स के साथ उनकी वाइफ और बच्चे भी साथ थे। इससे कुछ दिन पहले क्रिकेटर्स की वाइफ एकसाथ टाइगर रिजर्व घूमने गई थीं। आगे की स्लाइड्स में देखें, साउथ अफ्रीका के मजिकी सफारी में एन्जॉय कर रहे क्रिकेटर्स के फोटो...</b>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/front-pic_1516512483.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305450",
            "title": "Filmfare अवॉर्ड में पहुंचीं प्रेग्नेंट प्रिटी!, रेखा ने सिखाया विद्या बालन को डांस",
            "filename": "ENT-BPAR-IFTM-pregnant-preity-zinta-shah-rukh-khan-and-other-celebs-filmfare-awards-inside-pho-5796143-PHO",
            "file_name": "ENT-BPAR-IFTM-pregnant-preity-zinta-shah-rukh-khan-and-other-celebs-filmfare-awards-inside-pho-5796143-PHO.html",
            "slug_intro": "शनिवार को मुंबई में 63वें फिल्मफेयर अवॉर्ड्स का आयोजन किया गया। इसमें कई बॉलीवुड सेलेब्स पहुंचे।",
            "channel_slno": "521",
            "cat_id": "8096",
            "priority_level_1": "12",
            "story_id": "121073460",
            "storyid": "121073460",
            "imageId": "121073460",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/ENT-BPAR-IFTM-pregnant-preity-zinta-shah-rukh-khan-and-other-celebs-filmfare-awards-inside-pho-5796143-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/ENT-BPAR-IFTM-pregnant-preity-zinta-shah-rukh-khan-and-other-celebs-filmfare-awards-inside-pho-5796143-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/jio-inside4_1516514535.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "14",
            "traffic": "7391",
            "pubdate": "2018-01-21 14:09:00",
            "created_on": "2018-01-21 11:01:00",
            "pcat_id": "3998",
            "pcat_name": "Entertainment",
            "firstParagraph": "मुंबई.</b> शनिवार को मुंबई में 63वें फिल्मफेयर अवॉर्ड्स का आयोजन किया गया। इसमें कई बॉलीवुड सेलेब्स पहुंचे। हाल ही में इस इवेंट की इनसाइड फोटोज सामने आई हैं जिसमें प्रिटी जिंटा एक्ट्रेस दीया मिर्जा के साथ बैठीं टाइम स्पेंड करतीं नजर आ रही हैं। प्रिटी को लेकर खबरें हैं कि वे इन दिनों प्रेग्नेंट हैं और अपना फर्स्ट बेबी एक्सपेक्ट कर रही हैं। बता दें, प्रिटी ने ब्वॉयफ्रेंड जीन गुडइनफ को करीब पांच साल डेट करने के बाद 29 फरवरी, 2016 को लॉस एंजिलिस में प्राइवेट सेरेमनी में शादी की थी। विद्या को डांस सिखाती दिखीं रेखा...</b></p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/jio-inside4_1516514535.jpg",
            "cat_url": ""
        },
        {
            "slno": "120305127",
            "title": "DB SPL: भिखारी जैसा दिखने लगा था, मेरे मर्द होने पर भी शक करते थे: असली पैडमेन मुरुगनंथम",
            "filename": "MH-MUM-OMC-LCL-padman-arunachalam-muruganantham-special-interview-by-bhaskar-5795970-PHO",
            "file_name": "MH-MUM-OMC-LCL-padman-arunachalam-muruganantham-special-interview-by-bhaskar-5795970-PHO.html",
            "slug_intro": "मेरी शादी 1998 में हुई थी। पत्नी को पीरियड्स के दौरान बेहद गंदे कपड़े इस्तेमाल करते देखा तो अंदर तक हिल गया।",
            "channel_slno": "521",
            "cat_id": "5472",
            "priority_level_1": "12",
            "story_id": "121072986",
            "storyid": "121072986",
            "imageId": "121072986",
            "flag_v": "0",
            "video_flag": "0",
            "url": "https://m.bhaskar.com/news/MH-MUM-OMC-LCL-padman-arunachalam-muruganantham-special-interview-by-bhaskar-5795970-PHO.html?ref=rec",
            "link": "https://m.bhaskar.com/news/MH-MUM-OMC-LCL-padman-arunachalam-muruganantham-special-interview-by-bhaskar-5795970-PHO.html?ref=rec",
            "tpvs": "",
            "cat_type": "NEWS-REC",
            "image": "https://i3.dainikbhaskar.com/thumbnails/116x90/web2images/www.bhaskar.com/2018/01/21/padmen_1516492958.jpg",
            "image_attr": "width=\"116\" height=\"90\"",
            "targetblank": "",
            "image_count": "3",
            "traffic": "5469",
            "pubdate": "2018-01-21 09:05:00",
            "created_on": "2018-01-21 03:01:00",
            "pcat_id": "2318",
            "pcat_name": "Maharashtra",
            "firstParagraph": "चेन्नई.   </b>तमिलनाडु के मुरुगनंथम सोशल आंत्रप्रेन्योर हैं। पीरियड्स की परेशानियों को लेकर अवेयरनेस फैला रहे हैं। सस्ते सेनेटरी नैपकिन बनाने वाली मशीन बनाई है। पद्मश्री से सम्मानित मुरुगनंथम से दैनिक भास्कर के जेसी शिबु ने बातचीत की। इसमें उन्होंने वो बातें बताईं जिन्होंने उन्हें झकझोर दिया था। अक्षय कुमार की फिल्म पैडमेन इन्हीं मुरुगनंथम पर बनी है। अक्षय खुद मुरुगनंथम से बहुत इन्सपायर हैं। </p>\r\n\r\n\r\n\r\n</p>",
            "img_type": 3,
            "infog": 0,
            "images": [],
            "last_slide_img": "https://i3.dainikbhaskar.com/thumbnails/321x278/web2images/www.bhaskar.com/2018/01/21/padmen_1516492958.jpg",
            "cat_url": "maharashtra/mumbai/"
        }*/
    ]
}